import express from "express";
import router from "./routes/user-routes.js";
import blogrouter from "./routes/blog-routes.js";
import cors from "cors";
const app = express();
app.use(cors());
app.use(express.json());
app.use("/user", router);
app.use("/blog", blogrouter);
export default app;
